import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Stage from "@/components/Stage";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#a1f3e5] min-h-screen">
        <Header></Header>
        <Stage></Stage>
      </main>
    </>
  );
}
